Add eslint to build script

diff --git a/scripts/build/build_all b/scripts/build/build_all
--- a/scripts/build/build_all
+++ b/scripts/build/build_all
@@ -24,4 +24,11 @@ if [ $? -ne "0" ]; then
 	exit 1
 fi
 
+$(npm bin)/eslint .eslintrc.json
+
+if [ $? -ne "0"]; then
+    echo "ESLint Failed"
+    exit 1
+fi
+
 exit $?
